# =============================================================================
# postgres-secret.yaml — credenciais do Postgres (namespace blue-green)
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: blue-green
type: Opaque
stringData:
  POSTGRES_USER:     appuser
  POSTGRES_PASSWORD: mudar123
  POSTGRES_DB:       appdb
