# =============================================================================
# service-green.yaml — Service ClusterIP do slot green
# =============================================================================
apiVersion: v1
kind: Service
metadata:
  name: app-go-green
  namespace: blue-green
  labels:
    app: app-go
    slot: green
spec:
  type: ClusterIP
  selector:
    app: app-go
    slot: green
  ports:
    - name: http
      port: 5000
      targetPort: 5000
